### ISSUE TITLE
should be possible to specify serial port rather than the first MicroPython-ish device

### ISSUE THREAD

**Issue by scruss** [harbaum/upide#1]
upide fails for me as I have numerous serial devices attached, and the first device upide finds is a CircuitPython device doing something else entirely.

My serial ports, in `/dev/serial/by-id` in order of discovery with a note on what they are used for:

    crw-rw---- 1 root dialout 4, 64 Aug 18 14:38 /dev/ttyS0                                                                         # 8-bit development system
    lrwxrwxrwx 1 root root  13 Aug  2 20:30 usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0 -> ../../ttyUSB0        # plotter
    lrwxrwxrwx 1 root root  13 Aug  2 20:30 usb-1a86_7523-if00-port0 -> ../../ttyUSB1                                               # legacy PDP-8 computer
    lrwxrwxrwx 1 root root  13 Aug 17 08:49 usb-Seeed_Seeeduino_XIAO_F5C354BD649375050213E2037213A0FF-if00 -> ../../ttyACM0         # CircuitPython volume control
    lrwxrwxrwx 1 root root  13 Aug  2 20:30 usb-MicroPython_Pyboard_Virtual_Comm_Port_in_FS_Mode_336D386B3339-if01 -> ../../ttyACM1 # F407 MicroPython development board
    lrwxrwxrwx 1 root root  13 Aug 15 14:55 usb-Raspberry_Pi_Pico_E66058388380772D-if00 -> ../../ttyACM2                            # Pico running something else entirely

upide takes a while to enumerate through all the ports, and then assumes /dev/ttyACM0 is the one I want to talk to. But it's a CircuitPython device that I need it to leave alone. upide fails with:

    , line 16, in listdir
    AttributeError: 'str' object has no attribute 'encode'

Full trace below:

    qt.svg: Cannot open file '/home/scruss/python/upide/assets/console_prompt.svg', because: No such file or directory
    qt.svg: Cannot open file '/home/scruss/python/upide/assets/console_prompt.svg', because: No such file or directory
    Board init
    Board 1 <bound method Window.on_scan_result of <__main__.Window object at 0x7f5ede192700>> None
    Trying to auto detect
    Checking port /dev/ttyS0 - ttyS0
    trying to open /dev/ttyS0
    Probing /dev/ttyS0
    ctrl-c sent
    ctrl-c sent
    RX: b'\xfc\xf0\xfc\xfc\xf0\xfc'
    No prompt
    Probing /dev/ttyS0
    ctrl-c sent
    ctrl-c sent
    RX: b'\xfc\xf0\xfc\xfc\xf0\xfc\xfc\xf0\xfc'
    No prompt
    Checking port /dev/ttyUSB1 - ttyUSB1
    trying to open /dev/ttyUSB1
    Probing /dev/ttyUSB1
    ctrl-c sent
    ctrl-c sent
    No prompt
    Probing /dev/ttyUSB1
    ctrl-c sent
    ctrl-c sent
    No prompt
    Checking port /dev/ttyUSB0 - USB-Serial Controller D
    trying to open /dev/ttyUSB0
    Probing /dev/ttyUSB0
    ctrl-c sent
    ctrl-c sent
    No prompt
    Probing /dev/ttyUSB0
    ctrl-c sent
    ctrl-c sent
    No prompt
    Checking port /dev/ttyACM0 - Seeeduino XIAO - CircuitPython CDC control
    trying to open /dev/ttyACM0
    Probing /dev/ttyACM0
    ctrl-c sent
    ctrl-c sent
    RX: b'\r\n>>> \r\n>>> \r\n>>> \r\n>>> '
    RX: b'\r\n>>> \r\nraw REPL; CTRL-B to exit\r\n>'
    thread done
    Board 2 <bound method Window.on_version of <__main__.Window object at 0x7f5ede192700>> None
    for i in os.uname(): print( i )
    RX: b'\r\n\r\nAdafruit CircuitPython 6.1.0 on 2021-01-21; Seeeduino XIAO with samd21g18\r\n>>> \r\n>>> \r\nraw REPL; CTRL-B to exit\r\n>'
    RX: b'OKsamd21\r\nsamd21\r\n6.1.0\r\n6.1.0 on 2021-01-21\r\nSeeeduino XIAO with samd21g18\r\n\x04\x04>'
    thread done
    Board 3 <bound method Window.on_listdir of <__main__.Window object at 0x7f5ede192700>> None
    replDo 
    import os
    def listdir(path):
        try:
            children = os.listdir(path)
        except OSError:
            try:
                size = os.stat(path)[6]
                return size
            except:
                return -2
        else:
            files = [ ]
            for child in children:
                # catch broken entries on unformatted pyboard
                if child.encode()[0] == 255:
                    return -2
    
                if path == '/': path = ''
                files.append([ child, listdir(path + '/' + child)])
            return files
    
    print(listdir("/"))
    
    RX: b'\r\n\r\nAdafruit CircuitPython 6.1.0 on 2021-01-21; Seeeduino XIAO with samd21g18\r\n>>> \r\n>>> \r\nraw REPL; CTRL-B to exit\r\n>'
    RX: b'OK\x04Traceback (most recent call last):\r\n  File "<stdin>", line 23, in <module>\r\n  File "<stdin>", line 16, in listdir\r\nAttributeError: \'str\' object has no attribute \'encode\'\r\n\x04>'
    Exception in BoardTread(): (<class 'RuntimeError'>, RuntimeError('Traceback (most recent call last):\r\n  File "<stdin>", line 23, in <module>\r\n  File "<stdin>", line 16, in listdir\r\nAttributeError: \'str\' object has no attribute \'encode\''), <traceback object at 0x7f5ed5d424c0>)
    Report: Traceback (most recent call last):
      File "<stdin>", line 23, in <module>
      File "<stdin>", line 16, in listdir
    AttributeError: 'str' object has no attribute 'encode'
    thread done

**Comment by harbaum** [comment]
Yes, i expected problems like that. Things may even be worse with systems where totally different serial connected devices may not like the probing at all. Also the current solution would not allow you to have multiple µP devices connected at the same time. Only the first one detected would be usable by upide.

But this tool is intended for total beginners and I don't expect them to understand COM/tty ports and their meaning. A few ACM devices can have custom information in the descriptors which would be displayed. But generic chips like the CH340 show up as "USB Serial" which does not give a useful hint for beginners.

There are several possible solutions:

- If the gui comes up in a usable state for you I could add some means to manually switch the port
- I could open an initial dialog asking the user whether he wants to scan or manually select a port
- I could allow the user to e.g. store port information somewhere like e.g. rename the binary to something upide_com3.exe to indicate a specific port to use

So far I've avoided to store anything on the PC itself. Thus I would not store any port information by now.

Any ideas?

**Comment by scruss** [comment]
Thanks for the response. I'd go with the initial dialogue. While the CH340 appears utterly generic, there are also a bunch of MicroPython boards that use them.

I do completely agree with your "don't store anything locally" policy and goals to keep this minimal

**Comment by harbaum** [comment]
But that initial dialog would show up every time you start the IDE. And it's useful only for the fraction of people who have many serial devices connected which - as you said - likely aren't the audience for this IDE anyway.

**Comment by scruss** [comment]
Can you scan ports, and if there's more than one serial port, open the dialogue?

The reason I'm picky about not opening the first device is that I've worked in assistive technology in the past. Many regular users (who coincidentally are people with disabilities) have a couple of things hanging off serial ports just to be able to access computers at all. I'm not saying go out your way to provide accessibility, maybe please don't block people who have no choice in how they access the computer.

**Comment by aivarannamaa** [comment]
A tip for implementing port listing -- PySerial has certain problems on Windows and macOS, which are worked around by https://github.com/adafruit/Adafruit_Board_Toolkit. See https://github.com/adafruit/Adafruit_Board_Toolkit/issues/1 for details.

The name of the library implies it's specific to Adafruit/CircuitPython, but you can use only the PySerial fix from it.

**Comment by harbaum** [comment]
Adding a port selection dialog for those who deal with multiple devices affects all users which don't want or need this feature.

Thus the current version allows to rename the binary from upide.exe (or upide under linux or upide.py) to upide_noscan.exe (or upide_noscan or upide_noscan.py). The renamed binary will then not scan for ports on startup but instead open a little dialog to let the user select a port.

**Comment by harbaum** [comment]
I'll close this as the latest release now has the ability to do so.

**Comment by jaimet** [comment]
> Thus the current version allows to rename the binary from upide.exe (or upide under linux or upide.py) to upide_noscan.exe (or upide_noscan or upide_noscan.py). The renamed binary will then not scan for ports on startup but instead open a little dialog to let the user select a port.

@harbaum Could you please add this info to [the documentation](https://github.com/harbaum/upide/blob/main/README.md)? Thank you.
