### ISSUE TITLE
Mac build will not open

### ISSUE THREAD

**Issue by andypiper** [harbaum/upide#12]
Opening the latest release on an M1 Pro MacBook results in an error:

`“upide” is damaged and can’t be opened.`

I've not tried building it locally yet, I am guessing this could be an arch (ARM vs Intel) issue?

**Comment by andypiper** [comment]
OK, built locally, but had to install a couple of things. I can confirm that the current git version does work on an M1 Pro Mac. I am guessing that PyInstaller only builds for the build machine's architecture by default (will look into this). I'll send a PR later with a couple of suggested improvements around this.

**Comment by harbaum** [comment]
I cannot tell you much about this as I've never owned any apple machines myself. This is being built on a virtual machine running catalina. So any feedback is welcome.
