### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by webdeb** [harbaum/upide#14]
Downloaded the dmg, tried the latest and the one before.
Moved into applications folder / or started from the dmg, it says the **program is damaged** and asks to move it to the bin.
Any idea?

**Comment by harbaum** [comment]
No, sorry. I don't have a Mac and haven't ever used one. This was built using MacOS inside virtualbox.

**Comment by webdeb** [comment]
Tried to build and it works fine, I like very much the simplicity. 👍

**Comment by harbaum** [comment]
Please provide a DMG file to share.

**Comment by webdeb** [comment]
of course https://filebin.net/vz2olzrghlkbsizy

**Comment by webdeb** [comment]
I am not sure if this will work on other systems, because apple has some rules for dev certificates etc.
