### ISSUE TITLE
modification big file

### ISSUE THREAD

**Issue by etno712** [harbaum/upide#2]
Hello,

Modifications and uploading of large files (e.g. 134 lines) almost systematically causes a crash (uPide does not respond anymore).

The last message in the terminal is:
```
RX: b'\r\nMicroPython v1.9.3-8-g63826ac5c on 2017-11-01; ESP module with ESP8266\r\nType "help()" for more information.\r\n>>> \r\n>>> \r\nraw REPL; CTRL-B to exit\r\n>'
RX: b'OK'
```
Otherwise great software. Thank you!

**Comment by harbaum** [comment]
Thanks for the report. I'll have a look at that.

**Comment by etno712** [comment]
my /temp folder was almost full. I don't have the problem anymore after emptying it.

**Comment by etno712** [comment]
Hello,

Finally the problem is there. I also found out that it is the PyQt5 of uPide that generates large volume of data in the /tmp (190MB). When you quit uPide with ctrl+c in the terminal, the files in /tmp are not deleted. You have to quit uPide with the interface if you don't want to see the /tmp full after several tries.

**Comment by harbaum** [comment]
You are using the fully bundled version that comes with all dependencies included. If you want to do so you need to make sure that there's enough memory for that. If you don't want that you can always run the upide.py script directly.

**Comment by harbaum** [comment]
This is how executables generated with pyinstaller behave in general. This is not uPIDE specific.

You may report this at the pyinstaller tool.
